// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeCompras.Data;

#nullable disable

namespace SistemaDeCompras.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811012610_AgregarNumeroAsientoContabilidad")]
    partial class AgregarNumeroAsientoContabilidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<decimal>("Existencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadMedidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Articulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Papel Bond 8.5x11",
                            Estado = 1,
                            Existencia = 50m,
                            Marca = "Report",
                            UnidadMedidaId = 2
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Tinta para impresora",
                            Estado = 1,
                            Existencia = 20m,
                            Marca = "HP",
                            UnidadMedidaId = 1
                        });
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.AsientoContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Asiento")
                        .HasColumnType("int");

                    b.Property<int>("CuentaCreditoId")
                        .HasColumnType("int");

                    b.Property<int>("CuentaDebitoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("MensajeError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoAsiento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OrdenCompraNumero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenCompraNumero");

                    b.ToTable("AsientosContables");
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 1,
                            Nombre = "Compras"
                        },
                        new
                        {
                            Id = 2,
                            Estado = 1,
                            Nombre = "Contabilidad"
                        },
                        new
                        {
                            Id = 3,
                            Estado = 1,
                            Nombre = "Almacen"
                        });
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentoId = 1,
                            Estado = 1,
                            Nombre = "Juan Perez"
                        },
                        new
                        {
                            Id = 2,
                            DepartamentoId = 3,
                            Estado = 1,
                            Nombre = "Maria Gomez"
                        });
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.OrdenCompra", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numero"));

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Numero");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("OrdenesCompra");
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.OrdenCompraDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrdenCompraNumero")
                        .HasColumnType("int");

                    b.Property<int>("UnidadMedidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("OrdenCompraNumero");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("DetallesOrdenCompra");
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CedulaRnc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CedulaRnc")
                        .IsUnique();

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CedulaRnc = "101000001",
                            Estado = 1,
                            NombreComercial = "Suplidora Nacional SRL"
                        },
                        new
                        {
                            Id = 2,
                            CedulaRnc = "101000002",
                            Estado = 1,
                            NombreComercial = "Distribuidora Caribe SRL"
                        });
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("UnidadesMedida");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Unidad",
                            Estado = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Caja",
                            Estado = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Libra",
                            Estado = 1
                        });
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.Articulo", b =>
                {
                    b.HasOne("SistemaDeCompras.Models.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany("Articulos")
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.AsientoContable", b =>
                {
                    b.HasOne("SistemaDeCompras.Models.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany("AsientosContables")
                        .HasForeignKey("OrdenCompraNumero")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OrdenCompra");
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.Empleado", b =>
                {
                    b.HasOne("SistemaDeCompras.Models.Entities.Departamento", "Departamento")
                        .WithMany("Empleados")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.OrdenCompra", b =>
                {
                    b.HasOne("SistemaDeCompras.Models.Entities.Departamento", "Departamento")
                        .WithMany("OrdenesCompra")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaDeCompras.Models.Entities.Empleado", "Empleado")
                        .WithMany("OrdenesCompra")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaDeCompras.Models.Entities.Proveedor", "Proveedor")
                        .WithMany("OrdenesCompra")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Departamento");

                    b.Navigation("Empleado");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.OrdenCompraDetalle", b =>
                {
                    b.HasOne("SistemaDeCompras.Models.Entities.Articulo", "Articulo")
                        .WithMany("DetallesOrdenCompra")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaDeCompras.Models.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenCompraNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeCompras.Models.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("OrdenCompra");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.Articulo", b =>
                {
                    b.Navigation("DetallesOrdenCompra");
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.Departamento", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("OrdenesCompra");
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.Empleado", b =>
                {
                    b.Navigation("OrdenesCompra");
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.OrdenCompra", b =>
                {
                    b.Navigation("AsientosContables");

                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.Proveedor", b =>
                {
                    b.Navigation("OrdenesCompra");
                });

            modelBuilder.Entity("SistemaDeCompras.Models.Entities.UnidadMedida", b =>
                {
                    b.Navigation("Articulos");
                });
#pragma warning restore 612, 618
        }
    }
}
